/**
 * Notes: 路由配置文件
 * User: CC
 * Date: 2020-10-14 07:00:00
 */

module.exports = {
	'queue/options': 'queue_controller@options',
	'queue/create': 'queue_controller@create',
	'queue/my_current': 'queue_controller@myCurrent',
	'queue/checkin': 'queue_controller@checkin',
	'queue/subscribe': 'queue_controller@subscribe',
	'queue/confirm': 'queue_controller@confirm',
	'queue/pay': 'queue_controller@pay',

	'driver/wxlogin': 'driver_controller@wxLogin',
	'driver/register': 'driver_controller@register',
	'driver/getphonenumber': 'driver_controller@getPhoneNumber',
	'driver/getinfo': 'driver_controller@getMyDetail',
	'driver/updateinfo': 'driver_controller@updateInfo',

	'storage/options': 'storage_controller@options',
	'storage/store_register': 'storage_controller@storeRegister',
	'storage/fetch_calc': 'storage_controller@fetchCalc',
	'storage/fetch_register': 'storage_controller@fetchRegister',
	'storage/my_current': 'storage_controller@myCurrent',
	'storage/pay': 'storage_controller@pay',

	'customer/login': 'customer_controller@login',
	'customer/home': 'customer_controller@home',
	'customer/plate_add': 'customer_controller@plateAdd',
	'customer/plate_del': 'customer_controller@plateDel',

	'forklift/login': 'forklift_controller@login',
	'forklift/my_task': 'forklift_controller@myTask',
	'forklift/complete': 'forklift_controller@complete',
	'forklift/grab': 'forklift_controller@grab',

	'storage_forklift/my_task': 'storage_forklift_controller@myTask',
	'storage_forklift/grab': 'storage_forklift_controller@grab',
	'storage_forklift/complete': 'storage_forklift_controller@complete',

	'admin/login': 'admin/admin_home_controller@adminLogin',
	'admin/check_setup': 'admin/admin_home_controller@checkSetup',
	'admin/home': 'admin/admin_home_controller@adminHome',
	'admin/clear_cache': 'admin/admin_home_controller@clearCache',
	'admin/queue_list': 'admin/admin_queue_controller@list',
	'admin/queue_create': 'admin/admin_queue_controller@createTask',
	'admin/queue_call': 'admin/admin_queue_controller@callSelected',
	'admin/queue_call_next': 'admin/admin_queue_controller@callNext',
	'admin/queue_auto_call': 'admin/admin_queue_controller@setAutoCall',
	'admin/queue_recall': 'admin/admin_queue_controller@recallCall',
	'admin/queue_assign': 'admin/admin_queue_controller@manualAssign',
	'admin/queue_fee_save': 'admin/admin_queue_controller@saveSceneFee',
	'admin/queue_settle': 'admin/admin_queue_controller@settle',
	'admin/queue_confirm_pay': 'admin/admin_queue_controller@confirmPay',
	'admin/queue_detail': 'admin/admin_queue_controller@detail',
	'admin/queue_history_list': 'admin/admin_queue_controller@historyList',
	'admin/queue_history_clear': 'admin/admin_queue_controller@historyClear',
	'admin/queue_history_clear_all': 'admin/admin_queue_controller@historyClearAll',
	'admin/queue_edit': 'admin/admin_queue_controller@edit',
	'admin/queue_cancel': 'admin/admin_queue_controller@cancel',
	'admin/queue_finish': 'admin/admin_queue_controller@finish',
	'admin/forklift_list': 'admin/admin_queue_controller@forkliftList',

	'admin/storage_list': 'admin/admin_storage_controller@list',
	'admin/storage_detail': 'admin/admin_storage_controller@detail',
	'admin/storage_call': 'admin/admin_storage_controller@call',
	'admin/storage_auto_call': 'admin/admin_storage_controller@setAutoCall',
	'admin/storage_recall': 'admin/admin_storage_controller@recall',
	'admin/storage_assign': 'admin/admin_storage_controller@assign',
	'admin/storage_confirm_pay': 'admin/admin_storage_controller@confirmPay',
	'admin/storage_cancel': 'admin/admin_storage_controller@cancel',
	'admin/storage_history_list': 'admin/admin_storage_controller@historyList',
	'admin/storage_history_clear': 'admin/admin_storage_controller@historyClear',
	'admin/storage_history_clear_all': 'admin/admin_storage_controller@historyClearAll',
	'admin/storage_cabinet_list': 'admin/admin_storage_controller@cabinetList',
	'admin/storage_cabinet_save': 'admin/admin_storage_controller@cabinetSave',
	'admin/storage_cabinet_del': 'admin/admin_storage_controller@cabinetDel',
	'admin/storage_forklift_list': 'admin/admin_storage_controller@forkliftList',

	'admin/report_month': 'admin/admin_export_controller@queueMonthExport',
	'admin/report_url': 'admin/admin_export_controller@queueMonthGet',
	'admin/report_storage_month': 'admin/admin_export_controller@storageMonthExport',
	'admin/report_storage_url': 'admin/admin_export_controller@storageMonthGet',

	'admin/user_list': 'admin/admin_user_controller@getUserList',
	'admin/user_detail': 'admin/admin_user_controller@getUserDetailById',
	'admin/user_insert': 'admin/admin_user_controller@insertUser',
	'admin/user_edit': 'admin/admin_user_controller@editUser',
	'admin/user_status': 'admin/admin_user_controller@userStatus',
	'admin/user_del': 'admin/admin_user_controller@delUser',

	'admin/setup': 'admin/admin_mgr_controller@setupAdmin',
	'admin/admin_list': 'admin/admin_mgr_controller@getAdminList',
	'admin/admin_detail': 'admin/admin_mgr_controller@getAdminDetail',
	'admin/admin_insert': 'admin/admin_mgr_controller@insertAdmin',
	'admin/admin_edit': 'admin/admin_mgr_controller@editAdmin',
	'admin/admin_del': 'admin/admin_mgr_controller@delAdmin',
	'admin/admin_change_pwd': 'admin/admin_mgr_controller@changePwd',
	'admin/admin_reset_pwd': 'admin/admin_mgr_controller@resetPwd',

	'admin/customer_insert': 'admin/admin_customer_controller@insert',
	'admin/customer_edit': 'admin/admin_customer_controller@edit',
	'admin/customer_del': 'admin/admin_customer_controller@del',
};
